using System.ComponentModel.DataAnnotations;

namespace RechargePlatform.Common.DTOs;

/// <summary>
/// Prepaid mobile recharge execution request payload
/// </summary>
public class RechargeRequestDto
{
    /// <summary>Unique transaction ID generated by client/POS (e.g. TXN100001)</summary>
    /// <example>TXN100001</example>
    [Required(ErrorMessage = "TransactionId is required.")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "TransactionId must be between 3 and 50 characters.")]
    public string TransactionId { get; set; } = string.Empty;

    /// <summary>10-digit Indian subscriber mobile number starting with 6, 7, 8, or 9</summary>
    /// <example>9876543210</example>
    [Required(ErrorMessage = "MobileNumber is required.")]
    [RegularExpression(@"^[6-9]\d{9}$", ErrorMessage = "MobileNumber must be a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9.")]
    public string MobileNumber { get; set; } = string.Empty;

    /// <summary>Telecom operator: Jio, Airtel, Vi, or BSNL</summary>
    /// <example>Airtel</example>
    [Required(ErrorMessage = "Operator is required.")]
    public string Operator { get; set; } = string.Empty;

    /// <summary>Recharge amount in INR (Simulation rules: 100=Success, 200=Fail, 300=Timeout, 400=Drop, 500=Error, 299=Airtel)</summary>
    /// <example>299</example>
    [Range(1, 50000, ErrorMessage = "Amount must be between 1 and 50000 INR.")]
    public decimal Amount { get; set; }
}

public class RechargeResponseDto
{
    public long Id { get; set; }
    public string TransactionId { get; set; } = string.Empty;
    public string MobileNumber { get; set; } = string.Empty;
    public string Operator { get; set; } = string.Empty;
    public string OperatorName { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public string Status { get; set; } = string.Empty;
    public string? ProviderReference { get; set; }
    public string? ErrorMessage { get; set; }
    public DateTime CreatedDate { get; set; }
    public DateTime UpdatedDate { get; set; }
    public bool IsDuplicate { get; set; }
    public List<StatusHistoryDto>? History { get; set; }
}

public class StatusHistoryDto
{
    public long Id { get; set; }
    public string TransactionId { get; set; } = string.Empty;
    public string? OldStatus { get; set; }
    public string NewStatus { get; set; } = string.Empty;
    public string? Remarks { get; set; }
    public DateTime CreatedDate { get; set; }
}

/// <summary>
/// Query filters for paginated transaction retrieval
/// </summary>
public class TransactionFilterDto
{
    /// <summary>Filter by transaction status: SUCCESS, FAILED, PENDING, PROCESSING, NEW</summary>
    /// <example>SUCCESS</example>
    public string? Status { get; set; }

    /// <summary>Filter by operator: Jio, Airtel, Vi, BSNL</summary>
    /// <example>Airtel</example>
    public string? Operator { get; set; }

    /// <summary>Filter by 10-digit mobile number</summary>
    /// <example>9876543210</example>
    public string? MobileNumber { get; set; }

    /// <summary>Filter transactions from this start date (UTC)</summary>
    public DateTime? FromDate { get; set; }

    /// <summary>Filter transactions up to this end date (UTC)</summary>
    public DateTime? ToDate { get; set; }

    /// <summary>Page number for pagination (starts at 1)</summary>
    /// <example>1</example>
    public int PageNumber { get; set; } = 1;

    /// <summary>Number of items per page (default: 50)</summary>
    /// <example>20</example>
    public int PageSize { get; set; } = 50;
}

public class ReconcileResponseDto
{
    public string TransactionId { get; set; } = string.Empty;
    public string PreviousStatus { get; set; } = string.Empty;
    public string CurrentStatus { get; set; } = string.Empty;
    public string? ProviderReference { get; set; }
    public string Message { get; set; } = string.Empty;
    public DateTime ReconciledAt { get; set; } = DateTime.UtcNow;
}
